In [1]:
import numpy as np

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[11,12,13],[2,2,2]])

if arr1.shape !=arr2.shape:
    print ("Error: Given arrays are of not same size")
else:
    print ("Exponential of 2nd on 1st array is:  \n" , arr1**arr2)
        
#Using the built in power function

import numpy as np

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[11,12,13],[2,2,2]])

if arr1.shape !=arr2.shape:
    print ("Error: Given arrays are of not same size")
else:
    print ("Exponential of 2nd on 1st array is using built in function:\n" , np.power(arr1,arr2))

Exponential of 2nd on 1st array is:  
 [[      1    4096 1594323]
 [     16      25      36]]
Exponential of 2nd on 1st array is using built in function:
 [[      1    4096 1594323]
 [     16      25      36]]
